View(mtcars)
library(purrr)
library(tidyr)
library(ggplot2)
mtcars %>%keep(is.numeric) %>%gather() %>% ggplot(aes(value)) +facet_wrap(~ key, scales = "free") +geom_histogram()
boxplot(mtcars$mpg~mtcars$cyl,main="Boxplot Chart",xlab="CYL",ylab="milage",col=c("orange","red","yellow"))
